# Generated by Django 3.1 on 2021-02-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_memberstory_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberstory',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
