# Generated by Django 3.1 on 2021-02-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0003_memberstory_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberstory',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='memberstory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
