# Generated by Django 3.1 on 2021-02-16 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='last_change',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='version',
            field=models.CharField(max_length=8),
        ),
    ]
