# Generated by Django 3.1 on 2021-02-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_module_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
