# Generated by Django 3.1 on 2021-02-18 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_educationprofile_status'),
        ('course', '0005_course_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.PositiveIntegerField(null=True)),
                ('target_year', models.PositiveIntegerField(null=True)),
                ('project_type', models.CharField(choices=[('DS', 'Data Sains'), ('WD', 'Web Development'), ('QA', 'Quality Assurance')], max_length=8, null=True)),
                ('project_idea', models.TextField(blank=True, null=True)),
                ('current_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_projects', to='user.educationprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
