# Generated by Django 3.1 on 2021-02-17 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0005_course_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_study', models.CharField(max_length=128, null=True)),
                ('university_name', models.CharField(max_length=128, null=True)),
                ('current_semester', models.PositiveIntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
