# Generated by Django 3.1 on 2021-02-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20210218_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='legal_logo',
            new_name='school',
        ),
    ]
