# Generated by Django 3.1 on 2021-02-19 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0011_mentor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeproject',
            name='status',
            field=models.CharField(choices=[('WTG', 'WAITING'), ('APR', 'Approved')], default='WTG', max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='MentoringRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_pitching', models.TextField()),
                ('status', models.CharField(choices=[('WTG', 'WAITING'), ('APR', 'Approved')], default='WTG', max_length=8, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_requests', to='course.mentor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
