# Generated by Django 3.1 on 2021-02-22 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0013_auto_20210219_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLearnRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WTG', 'Waiting'), ('APR', 'Approved'), ('RJT', 'Rejected')], default='WTG', max_length=8, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_learns', to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_learns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
