# Generated by Django 3.1 on 2021-02-07 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesionalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=128)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesional_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
