# Generated by Django 3.1 on 2021-02-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profesionalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city_domicile',
            field=models.CharField(default='Depok', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age_joined',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
