# Generated by Django 3.1 on 2021-02-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210218_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprofile',
            name='college_level',
            field=models.CharField(choices=[('DPM', 'Diploma'), ('SJN', 'Sarjana'), ('MTR', 'Master'), ('DTR', 'Doktor')], max_length=8, null=True),
        ),
    ]
