# Generated by Django 3.1 on 2021-02-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_educationprofile_college_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprofile',
            name='status',
            field=models.CharField(choices=[('WTG', 'WAITING'), ('APR', 'Approved')], default='WTG', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city_domicile',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
