# Generated by Django 3.1 on 2021-02-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210218_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationprofile',
            name='status',
        ),
    ]
