# Generated by Django 3.1 on 2021-02-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210218_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprofile',
            name='status',
            field=models.CharField(choices=[('WTG', 'WAITING'), ('APR', 'Approved')], default='WTG', max_length=8, null=True),
        ),
    ]
